// GENERATED by tools/gen_manifests.py from tools/cheat_list.py: do not edit.
#ifndef __GEN_CHEATS_H__
#define __GEN_CHEATS_H__

#include "recomp_api.h"
#include "reo_mem.h"
#include "reo_master.h"

#define REO_COND_infinite_ammo 0
#define REO_COND_cj_infinite_ammo 1
#define REO_COND_cb_extra_ammo 2
#define REO_COND_cb_max_infinite_ammo 3
#define REO_COND_mc_infinite_ammo_all_weapons 4
#define REO_COND_infinite_items 5
#define REO_COND_cb_no_zombie_over_time 6
#define REO_COND_cb_no_zombie_when_bitten 7
#define REO_COND_one_hit_kills 8
#define REO_COND_cb_enemies_dont_damage 9
#define REO_COND_cb_zombie_after_death 10
#define REO_COND_cb_infinite_health_on 11
#define REO_COND_cb_infinite_health_32 12
#define REO_COND_cb_infinite_health_16 13
#define REO_COND_mc_freeze_escape_time_l2 14
#define REO_COND_mc_reset_escape_time_l2 15
#define REO_COND_mc_infinite_escape_time 16
#define REO_COND_cj_infinite_time 17
#define REO_COND_mc_virus_level_never_goes_up 18
#define REO_COND_cb_l1_select_infection 19
#define REO_COND_cj_zombies_dont_move 20
#define REO_COND_cj_collection_opened 21
#define REO_COND_cj_scenarii_opened 22
#define REO_COND_COUNT 23

typedef struct { u32 addr; u32 word; } Reo_Guard;
typedef struct { u32 cond; u32 value; } Reo_Choice;
typedef struct { u32 pc; u32 original; u32 guardFirst; u32 guardCount; u32 choiceFirst; u32 choiceCount; } Reo_Site;

static const Reo_Guard kReoGuards[] = {
    { 0x005B1FF8u, 0x00121E3Cu },
    { 0x005B1FF8u, 0x00121E3Cu },
    { 0x005B2178u, 0x00121E3Cu },
    { 0x005B2178u, 0x00121E3Cu },
    { 0x005B2178u, 0x00121E3Cu },
    { 0x00667E54u, 0x0C199FA4u },
    { 0x0066015Cu, 0x0C199FE4u },
    { 0x006407F4u, 0x00C0882Du },
    { 0x00660B0Cu, 0x0080802Du },
    { 0x0065FD14u, 0x0220202Du },
    { 0x006607F4u, 0x84234200u },
    { 0x006607F4u, 0x84234200u },
    { 0x0068C7D0u, 0x848300A8u },
    { 0x0068C7D0u, 0x848300A8u },
    { 0x00667E54u, 0x0C199FA4u },
    { 0x00667E24u, 0x4600BDE4u },
    { 0x00667E54u, 0x0C199FA4u },
    { 0x0069650Cu, 0x0C16061Cu },
    { 0x0057C4F0u, 0x24423BF4u },
    { 0x0057C510u, 0x8CA30000u },
    { 0x00581C04u, 0x8C424078u },
};

static const Reo_Choice kReoChoices[] = {
    { REO_COND_infinite_ammo, 0x00000000u },
    { REO_COND_cj_infinite_ammo, 0x00000000u },
    { REO_COND_cb_extra_ammo, 0x24820001u },
    { REO_COND_cb_max_infinite_ammo, 0x24030063u },
    { REO_COND_mc_infinite_ammo_all_weapons, 0x24820000u },
    { REO_COND_infinite_items, 0x00000000u },
    { REO_COND_infinite_items, 0x00000000u },
    { REO_COND_infinite_items, 0x00000000u },
    { REO_COND_cb_no_zombie_over_time, 0x00000000u },
    { REO_COND_cb_no_zombie_when_bitten, 0x00000000u },
    { REO_COND_one_hit_kills, 0xA6620138u },
    { REO_COND_cb_enemies_dont_damage, 0x00000000u },
    { REO_COND_cb_zombie_after_death, 0x1000001Du },
    { REO_COND_cb_infinite_health_on, 0x2403270Fu },
    { REO_COND_cb_infinite_health_32, 0xAE030544u },
    { REO_COND_cb_infinite_health_16, 0xA6030544u },
    { REO_COND_mc_freeze_escape_time_l2, 0x24630000u },
    { REO_COND_mc_reset_escape_time_l2, 0x24630000u },
    { REO_COND_mc_infinite_escape_time, 0x24630000u },
    { REO_COND_cj_infinite_time, 0x00000000u },
    { REO_COND_mc_virus_level_never_goes_up, 0x34100000u },
    { REO_COND_cb_l1_select_infection, 0x24900000u },
    { REO_COND_cj_zombies_dont_move, 0x00000000u },
    { REO_COND_cj_collection_opened, 0x00000000u },
    { REO_COND_cj_scenarii_opened, 0x00000000u },
};

// pc, original word, guards, replacements (the first whose condition is on wins).
static const Reo_Site kReoSites[] = {
    { 0x005B200Cu, 0xA6020024u, 0, 1, 0, 2 }, // game.bin sh v0,0x24(s0)
    { 0x005B2008u, 0x2482FFFFu, 1, 1, 2, 3 }, // game.bin addiu v0,a0,-1 (delay slot)
    { 0x005B218Cu, 0xA6020024u, 2, 1, 5, 1 }, // game.bin sh v0,0x24(s0)
    { 0x005B21A0u, 0x14430003u, 3, 1, 6, 1 }, // game.bin bne v0,v1,0x005B21B0
    { 0x005B51B4u, 0x0000102Du, 4, 1, 7, 1 }, // game.bin move v0,zero
    { 0x00667E5Cu, 0xAE300BACu, 5, 1, 8, 1 }, // game.bin sw s0,0xbac(s1)
    { 0x00660160u, 0xAE220BACu, 6, 1, 9, 1 }, // game.bin sw v0,0xbac(s1) (delay slot)
    { 0x00640800u, 0x1062000Cu, 7, 1, 10, 1 }, // game.bin beq v1,v0,0x00640834
    { 0x00660B18u, 0x10600003u, 8, 1, 11, 1 }, // game.bin beqz v1,0x00660B28
    { 0x0065FD38u, 0x1443001Du, 9, 1, 12, 1 }, // game.bin bne v0,v1,0x0065FDB0
    { 0x00660800u, 0x86030544u, 10, 1, 13, 1 }, // game.bin lh v1,0x544(s0)
    { 0x00660808u, 0x00000000u, 11, 1, 14, 2 }, // game.bin nop (delay slot)
    { 0x0068C7DCu, 0x2463FFFFu, 12, 1, 16, 3 }, // game.bin addiu v1,v1,-1
    { 0x0068C7E0u, 0xA48300A8u, 13, 1, 19, 1 }, // game.bin sh v1,0xa8(a0)
    { 0x00667E58u, 0x0200302Du, 14, 1, 20, 1 }, // game.bin move a2,s0 (delay slot)
    { 0x00667E28u, 0x4410B800u, 15, 2, 21, 1 }, // game.bin mfc1 s0,$f23
    { 0x00696514u, 0x92020C82u, 17, 1, 22, 1 }, // game.bin lbu v0,0xc82(s0)
    { 0x0057C518u, 0x0003100Au, 18, 2, 23, 1 }, // demo.bin movz v0,zero,v1
    { 0x00581C14u, 0x10400072u, 20, 1, 24, 1 }, // demo.bin beqz v0,0x00581DE0
};

// The conditions of the sites, once per frame: option On, its device's master code On, and the pad for a joker.
static inline void Reo_ComputeConds(u32* cond, u32* latch) {
    u32 armax = Reo_MasterArmax();
    u32 cb = Reo_MasterCodeBreaker();
    u32 gs = Reo_MasterGameShark();
    u32 on;

    on = cb && (Reo_Opt("infinite_ammo") != 0);
    cond[REO_COND_infinite_ammo] = on;
    on = armax && (Reo_Opt("cj_infinite_ammo") != 0);
    cond[REO_COND_cj_infinite_ammo] = on;
    on = cb && (Reo_Opt("cb_extra_ammo") != 0);
    cond[REO_COND_cb_extra_ammo] = on;
    on = cb && (Reo_Opt("cb_max_infinite_ammo") != 0);
    cond[REO_COND_cb_max_infinite_ammo] = on;
    on = gs && (Reo_Opt("mc_infinite_ammo_all_weapons") != 0);
    cond[REO_COND_mc_infinite_ammo_all_weapons] = on;
    on = cb && (Reo_Opt("infinite_items") != 0);
    cond[REO_COND_infinite_items] = on;
    on = cb && (Reo_Opt("cb_no_zombie_over_time") != 0 || Reo_Opt("no_infection") != 0);
    cond[REO_COND_cb_no_zombie_over_time] = on;
    on = cb && (Reo_Opt("cb_no_zombie_when_bitten") != 0 || Reo_Opt("no_infection") != 0);
    cond[REO_COND_cb_no_zombie_when_bitten] = on;
    on = cb && (Reo_Opt("one_hit_kills") != 0);
    cond[REO_COND_one_hit_kills] = on;
    on = cb && (Reo_Opt("cb_enemies_dont_damage") != 0);
    cond[REO_COND_cb_enemies_dont_damage] = on;
    on = cb && (Reo_Opt("cb_zombie_after_death") != 0);
    cond[REO_COND_cb_zombie_after_death] = on;
    on = cb && (Reo_Opt("cb_infinite_health") != 0);
    cond[REO_COND_cb_infinite_health_on] = on;
    on = cb && (Reo_Opt("cb_infinite_health") == 2);
    cond[REO_COND_cb_infinite_health_32] = on;
    on = cb && (Reo_Opt("cb_infinite_health") == 1);
    cond[REO_COND_cb_infinite_health_16] = on;
    on = gs && (Reo_Opt("mc_freeze_escape_time_l2") != 0);
    cond[REO_COND_mc_freeze_escape_time_l2] = on && Reo_Pad(0x002B081Cu) == 0xFEFFu;
    on = gs && (Reo_Opt("mc_reset_escape_time_l2") != 0);
    cond[REO_COND_mc_reset_escape_time_l2] = on && Reo_Pad(0x002B081Cu) == 0xFEFFu;
    on = gs && (Reo_Opt("mc_infinite_escape_time") != 0);
    cond[REO_COND_mc_infinite_escape_time] = on;
    on = armax && (Reo_Opt("cj_infinite_time") != 0);
    cond[REO_COND_cj_infinite_time] = on;
    on = gs && (Reo_Opt("mc_virus_level_never_goes_up") != 0);
    cond[REO_COND_mc_virus_level_never_goes_up] = on;
    on = cb && (Reo_Opt("cb_l1_select_infection") != 0);
    if (!on) {
        latch[REO_COND_cb_l1_select_infection] = 0;
    } else {
        u32 pad = Reo_Pad(0x002B089Cu);
        if (pad == 0xFBFEu) {
            latch[REO_COND_cb_l1_select_infection] = 1;
        } else if (pad == 0xFFFFu) {
            latch[REO_COND_cb_l1_select_infection] = 0;
        }
    }
    cond[REO_COND_cb_l1_select_infection] = latch[REO_COND_cb_l1_select_infection];
    on = armax && (Reo_Opt("cj_zombies_dont_move") != 0);
    cond[REO_COND_cj_zombies_dont_move] = on;
    on = armax && (Reo_Opt("cj_collection_opened") != 0);
    cond[REO_COND_cj_collection_opened] = on;
    on = armax && (Reo_Opt("cj_scenarii_opened") != 0);
    cond[REO_COND_cj_scenarii_opened] = on;
}

static const u32 kVal_bh_result_points_best_record[] = { 0x0u, 0x0u, 0xFFu };
static const u32 kVal_bh_completion_time_best_record[] = { 0x0u, 0x0u, 0xFFu };
static const u32 kVal_bh_completion_time_rank[] = { 0x0u, 0x0u, 0x1u, 0x2u, 0x3u, 0x4u, 0x5u, 0x6u };
static const u32 kVal_bh_survivor_modifier[] = { 0x0u, 0x0u, 0x1u, 0x2u, 0x3u };
static const u32 kVal_cb_infinite_health[] = { 0x0u, 0x1u, 0x2u };
static const u32 kVal_bh_number_of_players[] = { 0x0u, 0x1u, 0x2u, 0x3u, 0x4u };
static const u32 kVal_bh_p1_alt_costume[] = { 0x0u, 0x0u, 0x1u, 0x2u, 0x3u, 0x4u, 0x5u };
static const u32 kVal_bh_p1_model[] = { 0x0u, 0x0u, 0x1u, 0x2u, 0x3u, 0x4u, 0x5u, 0x6u, 0x7u, 0x8u, 0xAu, 0xBu, 0xCu, 0xDu, 0xEu, 0x11u, 0x12u, 0x13u, 0x14u, 0x16u, 0x17u, 0x18u, 0x19u, 0x1Au, 0x1Bu, 0x1Cu, 0x1Du, 0x1Eu, 0x1Fu, 0x20u, 0x21u, 0x23u, 0x24u, 0x25u, 0x27u, 0x28u, 0x29u, 0x2Au, 0x2Bu, 0x2Cu, 0x2Du, 0x2Fu, 0x30u, 0x31u, 0x32u, 0x33u, 0x34u, 0x35u, 0x36u, 0x37u, 0x38u, 0x39u, 0x3Bu, 0x3Cu, 0x3Fu, 0x40u, 0x41u, 0x42u, 0x46u, 0x49u, 0x4Au, 0x51u, 0x52u };
static const u32 kVal_bh_p1_char_type[] = { 0x0u, 0x0u, 0x1u, 0x2u, 0x3u, 0x4u, 0x5u, 0x6u, 0x7u };
static const u32 kVal_bh_p1_damage[] = { 0x0u, 0x3F000000u, 0x40000000u, 0x40400000u, 0x40A00000u, 0x41200000u, 0x42C80000u, 0x4FFFFFFFu };
static const u32 kVal_bh_p1_speed_1[] = { 0x0u, 0x3FF00000u, 0x40000000u, 0x40400000u, 0x40800000u, 0x4FFFFFFFu };
static const u32 kVal_bh_p1_speed_2[] = { 0x0u, 0x3F000000u, 0x3FC00000u, 0x40000000u, 0x40400000u, 0x40800000u };
static const u32 kVal_bh_p1_status[] = { 0x0u, 0x0u, 0x1u, 0x2u, 0x3u, 0x4u, 0x5u, 0x6u, 0x7u, 0x8u, 0x9u, 0xCu, 0x10u, 0x14u, 0x18u, 0x1Cu, 0x20u, 0x24u, 0x28u, 0xFFu };
static const u32 kVal_bh_p1_virus_gauge_2[] = { 0x0u, 0x4FFFFFFFu, 0x1u };

#define REO_KEY_ITEM_TABLE "bh_item_values_table"
#define REO_ITEM_TABLE_COUNT 20
#define REO_ITEM_NAME_COUNT 134
#define REO_ITEM_PAST_COUNT 12

// Decisions, Decisions - Easy
static const u8 kReoItemTable0[] = { 0, 43, 77, 38, 54, 100, 100, 70, 49, 42, 59, 54, 70, 30, 21, 17, 42, 70, 100, 54, 77, 54, 42, 49, 54, 70, 6, 12, 30, 30, 59, 21, 21, 77, 43, 6, 14, 54, 21, 54, 100, 83, 70, 54, 77, 42, 61, 14, 70, 100, 17, 42, 54, 12, 70, 77, 21, 21, 100, 54, 54, 58, 94, 77, 17, 21, 42, 17, 42, 12, 13, 70, 100, 21, 21, 30, 17, 54, 54, 54, 100, 54, 77, 42, 42, 70, 61, 21, 59, 2, 27, 77, 42, 42, 103, 17, 42, 70, 70, 27, 43, 42, 71, 54, 54, 100, 59, 27, 10, 42, 71, 17, 77, 42, 94, 94, 12, 12, 98, 17, 14, 83, 100, 77, 17, 59, 42, 12, 11, 70, 54, 98, 42, 70, 54, 77, 54, 21, 70, 49, 100, 59, 11, 54, 21, 77, 70, 21, 94, 43, 13, 54, 70, 83, 70, 42, 70, 59, 42, 12, 11, 100, 39, 39, 39, 39, 39, 77, 6, 14, 17, 30, 49, 42, 59, 96, 105, 128, 32, 23, 101, 125, 125, 22, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 78 };
// Decisions, Decisions - Hard
static const u8 kReoItemTable1[] = { 0, 43, 38, 54, 100, 77, 49, 42, 59, 54, 65, 21, 17, 65, 100, 54, 49, 54, 5, 12, 21, 59, 54, 77, 43, 5, 14, 54, 21, 100, 65, 54, 77, 61, 14, 65, 100, 42, 54, 12, 65, 21, 100, 54, 59, 38, 21, 54, 12, 42, 65, 21, 28, 17, 54, 54, 77, 42, 54, 65, 32, 21, 59, 43, 77, 43, 103, 17, 42, 77, 65, 30, 43, 77, 54, 100, 59, 28, 10, 54, 65, 15, 77, 42, 94, 94, 12, 97, 17, 59, 83, 100, 77, 17, 43, 12, 11, 65, 54, 97, 42, 65, 100, 54, 77, 54, 65, 59, 21, 11, 54, 21, 77, 21, 13, 54, 65, 83, 42, 65, 12, 98, 100, 39, 39, 39, 39, 39, 77, 17, 30, 54, 60, 96, 105, 128, 23, 101, 125, 125, 22, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 78 };
// Decisions, Decisions - Normal
static const u8 kReoItemTable2[] = { 0, 43, 77, 54, 100, 49, 42, 59, 54, 68, 28, 21, 17, 65, 100, 54, 77, 54, 42, 49, 68, 6, 12, 28, 54, 59, 21, 21, 77, 43, 6, 14, 54, 21, 100, 38, 54, 77, 42, 61, 14, 68, 100, 17, 42, 54, 12, 68, 77, 21, 21, 54, 58, 94, 68, 21, 12, 42, 13, 65, 100, 21, 30, 17, 54, 54, 54, 100, 77, 42, 65, 61, 21, 59, 5, 30, 77, 42, 42, 103, 17, 42, 68, 68, 30, 43, 42, 68, 54, 54, 100, 59, 30, 10, 68, 17, 77, 42, 94, 12, 12, 98, 17, 59, 83, 100, 77, 17, 43, 42, 12, 11, 65, 54, 98, 42, 65, 54, 54, 21, 65, 100, 57, 11, 54, 21, 77, 21, 94, 13, 54, 65, 83, 65, 65, 12, 98, 100, 39, 39, 39, 39, 39, 77, 6, 14, 42, 49, 42, 59, 96, 105, 128, 32, 23, 101, 125, 21, 77, 21, 94, 39, 39, 39, 39, 39, 39, 39, 39, 39, 78 };
// Decisions, Decisions - Very Hard
static const u8 kReoItemTable3[] = { 0, 43, 38, 54, 21, 77, 63, 49, 21, 21, 23, 100, 54, 54, 54, 11, 42, 28, 63, 43, 54, 38, 43, 63, 54, 21, 63, 21, 38, 42, 63, 14, 100, 11, 77, 100, 54, 43, 62, 21, 54, 11, 21, 28, 17, 54, 77, 42, 61, 32, 59, 43, 77, 43, 103, 42, 65, 29, 43, 77, 54, 59, 10, 63, 77, 77, 94, 12, 17, 63, 82, 100, 16, 55, 12, 11, 21, 61, 100, 54, 54, 42, 49, 11, 77, 54, 94, 77, 54, 63, 83, 63, 42, 12, 98, 21, 39, 39, 39, 39, 39, 5, 54, 56, 96, 105, 128, 101, 125, 125, 22, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 78 };
// Hellfire - Easy
static const u8 kReoItemTable4[] = { 0, 35, 81, 118, 50, 106, 101, 101, 101, 101, 42, 36, 59, 54, 59, 77, 109, 42, 54, 42, 21, 100, 109, 100, 21, 42, 117, 117, 42, 70, 117, 6, 54, 8, 70, 54, 54, 70, 77, 54, 11, 42, 54, 70, 2, 42, 59, 70, 117, 11, 100, 77, 117, 54, 54, 21, 100, 77, 21, 54, 117, 48, 117, 8, 6, 36, 36, 109, 18, 18, 12, 42, 36, 36, 54, 54, 117, 117, 31, 77, 77, 42 };
// Hellfire - Hard
static const u8 kReoItemTable5[] = { 0, 35, 81, 118, 50, 106, 101, 101, 101, 101, 54, 36, 54, 77, 38, 38, 59, 21, 54, 109, 100, 116, 116, 116, 54, 7, 54, 65, 77, 54, 100, 65, 3, 42, 31, 65, 11, 100, 116, 54, 100, 77, 21, 54, 46, 116, 3, 36, 109, 18, 18, 12, 36, 42, 54, 116, 31, 77, 38, 42 };
// Hellfire - Normal
static const u8 kReoItemTable6[] = { 0, 35, 81, 118, 50, 106, 101, 101, 101, 101, 54, 36, 59, 54, 59, 77, 54, 42, 21, 100, 109, 65, 54, 116, 116, 54, 65, 116, 54, 8, 65, 54, 54, 65, 77, 54, 11, 21, 65, 5, 42, 65, 116, 11, 100, 109, 116, 54, 21, 100, 77, 21, 54, 116, 47, 116, 100, 5, 36, 36, 109, 18, 18, 12, 42, 54, 54, 116, 31, 77, 42 };
// Hellfire - Very Hard
static const u8 kReoItemTable7[] = { 0, 35, 81, 118, 50, 106, 101, 101, 101, 101, 54, 77, 38, 77, 59, 21, 54, 21, 54, 38, 100, 115, 115, 54, 21, 63, 54, 11, 42, 42, 4, 107, 63, 11, 100, 115, 21, 54, 115, 107, 115, 100, 36, 31, 18, 12, 54, 36, 31, 77, 54 };
// Below Freezing Point - Easy
static const u8 kReoItemTable8[] = { 0, 74, 42, 54, 69, 77, 127, 130, 74, 42, 69, 129, 77, 45, 124, 69, 12, 42, 21, 21, 69, 54, 109, 54, 69, 42, 126, 80, 111, 77, 109, 54, 42, 52, 20, 72, 114, 42, 42, 74, 77, 54, 1, 77, 21, 69, 42, 109, 42, 54, 87, 100, 24, 133, 21, 52, 133 };
// Below Freezing Point - Hard
static const u8 kReoItemTable9[] = { 0, 73, 54, 54, 64, 124, 127, 130, 73, 42, 64, 129, 45, 124, 64, 11, 100, 21, 64, 54, 109, 100, 64, 54, 126, 80, 117, 100, 77, 109, 20, 69, 110, 42, 54, 54, 73, 77, 54, 117, 77, 21, 64, 42, 109, 54, 54, 85, 21, 24, 133, 52, 133 };
// Below Freezing Point - Normal
static const u8 kReoItemTable10[] = { 0, 74, 42, 54, 66, 77, 127, 130, 74, 42, 66, 129, 45, 124, 68, 11, 42, 21, 21, 68, 54, 109, 54, 66, 54, 126, 80, 117, 77, 109, 42, 52, 20, 70, 111, 42, 42, 74, 77, 54, 117, 77, 21, 66, 42, 109, 100, 54, 86, 21, 66, 24, 133, 21, 52, 133 };
// Below Freezing Point - Very Hard
static const u8 kReoItemTable11[] = { 0, 73, 54, 73, 127, 130, 63, 54, 54, 45, 124, 63, 54, 42, 54, 21, 63, 54, 109, 54, 54, 77, 54, 126, 80, 63, 54, 77, 53, 63, 63, 73, 20, 67, 117, 42, 77, 77, 77, 54, 54, 51, 100, 42, 54, 84, 21, 24, 129, 132, 77, 132, 51 };
// Outbreak - Easy
static const u8 kReoItemTable12[] = { 0, 42, 31, 59, 42, 54, 70, 70, 2, 21, 77, 70, 70, 104, 54, 70, 91, 100, 79, 11, 54, 131, 21, 70, 54, 83, 109, 70, 88, 21, 70, 77, 54, 44, 42, 122, 54, 59, 42, 61, 100, 95, 54, 70, 42, 54, 109, 77, 70, 42, 112, 109, 83, 119, 100, 21, 54, 100, 54, 100, 21, 88, 40, 41, 59, 54, 112, 9, 89, 120, 109, 109, 94, 9, 9, 95, 95, 9, 70, 2, 88, 42, 42, 113, 113, 83, 59 };
// Outbreak - Hard
static const u8 kReoItemTable13[] = { 0, 21, 31, 42, 54, 6, 21, 77, 77, 104, 54, 91, 11, 54, 131, 100, 57, 83, 57, 21, 44, 79, 63, 77, 54, 9, 54, 122, 54, 59, 42, 61, 54, 95, 120, 21, 42, 54, 109, 21, 117, 42, 63, 109, 83, 119, 100, 21, 54, 54, 100, 21, 88, 40, 59, 54, 63, 63, 109, 94, 9, 9, 95, 41, 63, 63, 5, 59, 42, 117, 83, 59 };
// Outbreak - Normal
static const u8 kReoItemTable14[] = { 0, 54, 31, 59, 42, 54, 2, 21, 65, 77, 77, 104, 54, 91, 100, 79, 11, 54, 131, 21, 65, 54, 83, 59, 65, 109, 21, 65, 77, 54, 44, 42, 122, 54, 59, 42, 61, 100, 95, 54, 65, 54, 109, 77, 65, 42, 117, 109, 83, 119, 100, 21, 54, 100, 54, 100, 21, 88, 40, 41, 59, 54, 65, 9, 117, 120, 109, 94, 9, 9, 95, 95, 9, 70, 2, 42, 42, 2, 2, 42, 59 };
// Outbreak - Very Hard
static const u8 kReoItemTable15[] = { 0, 21, 31, 54, 21, 54, 77, 77, 104, 91, 11, 54, 100, 5, 83, 42, 44, 79, 122, 54, 9, 21, 54, 57, 42, 61, 95, 120, 77, 59, 77, 63, 31, 54, 108, 83, 119, 21, 100, 54, 21, 54, 40, 57, 54, 63, 63, 93, 9, 9, 95, 41, 63, 59, 42, 117, 83, 59 };
// The Hive - Easy
static const u8 kReoItemTable16[] = { 0, 90, 59, 19, 19, 19, 19, 19, 19, 34, 33, 92, 102, 76, 42, 12, 104, 104, 104, 104, 70, 70, 70, 59, 61, 54, 54, 54, 54, 54, 54, 54, 100, 21, 21, 21, 21, 100, 100, 100, 100, 100, 42, 75, 75, 42, 42, 42, 77, 77, 31, 54, 54, 42, 42, 99, 99, 99, 99, 59, 70, 100, 121, 70, 11, 98, 26, 123, 70, 54, 70, 70, 70, 37, 37, 42, 37 };
// The Hive - Hard
static const u8 kReoItemTable17[] = { 0, 90, 59, 19, 19, 19, 19, 19, 34, 33, 92, 102, 76, 42, 11, 11, 104, 104, 104, 63, 54, 54, 54, 54, 21, 21, 21, 21, 21, 100, 100, 21, 100, 75, 75, 42, 42, 77, 77, 63, 42, 99, 99, 99, 31, 61, 100, 121, 63, 97, 75, 59, 26, 63, 31, 63, 37, 63, 37 };
// The Hive - Normal
static const u8 kReoItemTable18[] = { 0, 90, 59, 19, 19, 19, 19, 19, 19, 34, 33, 92, 102, 76, 42, 12, 104, 104, 104, 65, 65, 65, 59, 54, 54, 54, 54, 54, 54, 21, 21, 21, 21, 21, 100, 100, 100, 100, 42, 75, 75, 42, 42, 42, 77, 77, 31, 54, 42, 42, 99, 99, 99, 99, 61, 65, 100, 121, 65, 98, 97, 26, 123, 65, 54, 68, 37, 37, 37 };
// The Hive - Very Hard
static const u8 kReoItemTable19[] = { 0, 90, 57, 19, 19, 19, 19, 19, 75, 34, 33, 92, 102, 76, 57, 11, 11, 104, 104, 75, 121, 21, 54, 21, 54, 54, 21, 21, 21, 100, 54, 75, 104, 77, 77, 100, 54, 42, 99, 99, 99, 61, 100, 121, 63, 97, 75, 61, 25, 63, 31, 31, 37, 63, 63, 37 };
static const u8* const kReoItemTables[] = { kReoItemTable0, kReoItemTable1, kReoItemTable2, kReoItemTable3, kReoItemTable4, kReoItemTable5, kReoItemTable6, kReoItemTable7, kReoItemTable8, kReoItemTable9, kReoItemTable10, kReoItemTable11, kReoItemTable12, kReoItemTable13, kReoItemTable14, kReoItemTable15, kReoItemTable16, kReoItemTable17, kReoItemTable18, kReoItemTable19 };
static const u32 kReoItemTableLen[] = { 196, 153, 171, 123, 82, 60, 71, 51, 57, 53, 56, 53, 87, 72, 81, 58, 77, 59, 69, 56 };

typedef struct { const char* key; u32 addr; } Reo_Slot;
static const Reo_Slot kReoSlots[] = {
    { "bh_p1_item_slot_1", 0x004A68B4u },
    { "bh_p1_item_slot_2", 0x004A68B5u },
    { "bh_p1_item_slot_3", 0x004A68B6u },
    { "bh_p1_item_slot_4", 0x004A68B7u },
    { "bh_p1_special_item_slot", 0x004A68B8u },
    { "bh_p1_yoko_item_slot_5", 0x004A68B9u },
    { "bh_p1_yoko_item_slot_6", 0x004A68BAu },
    { "bh_p1_yoko_item_slot_7", 0x004A68BBu },
    { "bh_p1_yoko_item_slot_8", 0x004A68BCu },
};

typedef struct { const char* key; u32 addr; u32 bits; } Reo_Costume;
static const Reo_Costume kReoCostumes[] = {
    { "cb_costume_alyssa_all", 0x0031FB69u, 3 },
    { "cb_costume_alyssa_b", 0x0031FB69u, 1 },
    { "cb_costume_alyssa_c", 0x0031FB69u, 2 },
    { "cb_costume_cindy_all", 0x0031FB6Bu, 3 },
    { "cb_costume_cindy_b", 0x0031FB6Bu, 1 },
    { "cb_costume_cindy_c", 0x0031FB6Bu, 2 },
    { "cb_costume_david_all", 0x0031FB68u, 1 },
    { "cb_costume_david_b", 0x0031FB68u, 1 },
    { "cb_costume_george_all", 0x0031FB67u, 1 },
    { "cb_costume_george_b", 0x0031FB67u, 1 },
    { "cb_costume_jim_all", 0x0031FB66u, 1 },
    { "cb_costume_jim_b", 0x0031FB66u, 1 },
    { "cb_costume_kevin_all", 0x0031FB64u, 1 },
    { "cb_costume_kevin_b", 0x0031FB64u, 1 },
    { "cb_costume_mark_all", 0x0031FB65u, 1 },
    { "cb_costume_mark_b", 0x0031FB65u, 1 },
    { "cb_costume_yoko_all", 0x0031FB6Au, 3 },
    { "cb_costume_yoko_b", 0x0031FB6Au, 1 },
    { "cb_costume_yoko_c", 0x0031FB6Au, 2 },
};

static const u32 kReoCollectionMask[6] = { 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFBFE1FFFu, 0x00079FFFu };
static const u32 kReoCostumeMask[2] = { 0x01010101u, 0x03030301u };
static const u32 kReoNpcMask[3] = { 0x72400C40u, 0xFF03C200u, 0x03FFC0FBu };
#define REO_INFINITY_BITS 0x05000000u

#endif
